// gen-demo-go 生成 Docker_Manager_Go 的 demo key 源码文件。
// 用法: go run ./cmd/gen-demo-go <输出路径>
package main

import (
	"fmt"
	"os"

	"github.com/DockerManger/Docker_Manager_License/internal/crypto"
	"github.com/DockerManger/Docker_Manager_License/internal/license"
)

func main() {
	if len(os.Args) < 2 {
		panic("usage: go run ./cmd/gen-demo-go <out.go>")
	}
	priv, err := crypto.LoadPrivateKey("private/license.key")
	if err != nil {
		panic(err)
	}
	p := &license.Payload{
		Version:    license.CurrentVersion,
		KeyID:      "2026-01",
		LicenseID:  "DMG-DEMO0000000000000001",
		Product:    license.ProductDMG,
		Plan:       "pro",
		Features:   []string{"compose", "container_create", "appstore"},
		Customer:   "demo",
		IssuedAt:   1788007925,
		ExpiresAt:  4102444800, // 2100-01-01
		MaxDevices: 9999,
	}
	key, err := license.EncodeKey(p, priv.Private)
	if err != nil {
		panic(err)
	}
	src := fmt.Sprintf(`// Code generated by Docker_Manager_License cmd/gen-demo-go; DO NOT EDIT.
package service

// demoKeyV2 开发/演示用 V2 Key(2100 年过期,全功能;与内嵌公钥 "2026-01" 配对)。
// 仅限 DisplayVersion()=="unknown" 的开发构建使用(api 层 SEC-001 保护)。
const demoKeyV2 = %q
`, key)
	if err := os.WriteFile(os.Args[1], []byte(src), 0o644); err != nil {
		panic(err)
	}
	fmt.Printf("written %s (%d bytes)\n", os.Args[1], len(src))
}
